<?php
@define('OR_INSTR_GENERAL', '<strong>Note:</strong> This template requires some settings to work correctly in Serendipity.<br /><br /><strong>Blog title:</strong> The blog title ideally should not be longer than 14 characters <em>altogether</em> to fit the logo image in the upper left. (Blog title will be truncated to 14 characters automatically.)<br /><strong>Tagging of entries:</strong> The option <em>Show tags in footer?</em> needs to be set to <em>Smarty</em> in the configuration of the event plugin.<br /><hr />');
@define('OR_SUBSCRIBE', 'Subscribe to <b>RSS</b>');
@define('OR_BY', 'by');
@define('OR_FOR', 'for');
@define('OR_MORE', 'More');
@define('OR_NOTFOUND', 'Nichts gefunden');
@define('OR_REPLY', 'Leave a reply');
@define('OR_SUBMIT', 'Submit');
@define('OR_FORTHISENTRY', 'for this post');
@define('OR_SHOW_ADMIN_NAV', 'Display admin navigation (upper right)?');
@define('OR_SHOW_RSS_ADD', 'Display additional RSS link (upper right)?');
@define('OR_SHOW_ABOUT_BOX', 'Display about box in the sidebar?');
@define('OR_ABOUT_IMG', 'Image for about box (Recommended size: 85x85 pixels)');
@define('OR_ABOUT_TXT', 'Text for about box (*No* HTML allowed!)');
@define('OR_AUTHOR', 'Author');
@define('OR_SHOW_AD_BOX', 'Display ad box in the sidebar?');
@define('OR_SPONSORS', 'Sponsors');
@define('OR_AD_NAME_LEFT', 'Name of first sponsor (left box)');
@define('OR_AD_LINK_LEFT', 'Full URL of first sponsor (left box)');
@define('OR_AD_IMG_LEFT', 'Banner (125x125 pixels) of first sponsor (left box)');
@define('OR_AD_NAME_RIGHT', 'Name of second sponsor (right box)');
@define('OR_AD_LINK_RIGHT', 'Full URL of second sponsor (right box)');
@define('OR_AD_IMG_RIGHT', 'Banner (125x125 pixels) of second sponsor (right box)');
@define('OR_404H', 'Err... You got me! Error 404');
@define('OR_404S', 'Page Not Found or Does Not Exist!');
@define('OR_404M', 'But don\'t panic! All is not lost. Search for what you are looking for in the search bar on your right or use one of the links below.');
@define('NAVLINK_AMOUNT', 'Enter number of links in the navbar');
@define('NAV_LINK_TEXT', 'Enter the navbar link text');
@define('NAV_LINK_URL', 'Enter the full URL of your link');
