<?php
@define('OR_INSTR_GENERAL', '<strong>Hinweis:</strong> Dieses Template benötigt einige Einstellungen, damit es in Serendipity korrekt dargestellt wird.<br /><br /><strong>Blog-Titel:</strong> Der Blog-Titel sollte idealerweise nicht länger als <em>insgesamt</em> 14 Zeichen sein, damit er auf die Logografik oben links passt. (Der Blogtitel in diesem Logo wird automatisch auf 14 Zeichen gekürzt.)<br /><strong>Freie Artikel-Tags:</strong> Im Ereignis-Plugin muss <em>Zeige die Tags in der Fußzeile an?</em> auf <em>Smarty</em> gestellt werden.<br /><hr />');
@define('OR_SUBSCRIBE', '<b>RSS</b> abonnieren');
@define('OR_BY', 'von');
@define('OR_FOR', 'zu');
@define('OR_MORE', 'Mehr');
@define('OR_NOTFOUND', 'Nichts gefunden');
@define('OR_REPLY', 'Kommentieren');
@define('OR_SUBMIT', 'Senden');
@define('OR_FORTHISENTRY', 'für diesen Eintrag');
@define('OR_SHOW_ADMIN_NAV', 'Admin-Navigation (oben rechts) anzeigen?');
@define('OR_SHOW_RSS_ADD', 'Zusätzlichen RSS-Link (oben rechts) anzeigen?');
@define('OR_SHOW_ABOUT_BOX', 'About-Box in der Seitenleiste anzeigen?');
@define('OR_ABOUT_IMG', 'Bild für die About-Box (Empfohlenes Format: 85x85 Pixel)');
@define('OR_ABOUT_TXT', 'Text für die About-Box (*Kein* HTML verwenden!)');
@define('OR_AUTHOR', 'Autor');
@define('OR_SHOW_AD_BOX', 'Box für Werbung in der Seitenleiste anzeigen?');
@define('OR_SPONSORS', 'Sponsoren');
@define('OR_AD_NAME_LEFT', 'Name des ersten Sponsors (Box links)');
@define('OR_AD_LINK_LEFT', 'Voller URL zum ersten Sponsor (Box links)');
@define('OR_AD_IMG_LEFT', 'Banner (125x125 Pixel) des ersten Sponsors (Box links)');
@define('OR_AD_NAME_RIGHT', 'Name des zweiten Sponsors (Box rechts)');
@define('OR_AD_LINK_RIGHT', 'Voller URL zum zweiten Sponsor (Box rechts)');
@define('OR_AD_IMG_RIGHT', 'Banner (125x125 Pixel) des zweiten Sponsors (Box rechts)');
@define('OR_404H', 'Hmm... erwischt! Fehler 404');
@define('OR_404S', 'Seite nicht gefunden oder Seite existiert nicht!');
@define('OR_404M', 'Aber keine Panik! Noch ist nicht alles verloren. Man kann über das Suchformular in der rechten Seitenleiste suchen oder eine der folgenden Optionen nutzen:');
@define('NAVLINK_AMOUNT', 'Anzahl der Links in der Navigationsleiste');
@define('NAV_LINK_TEXT', 'Text des Navigationsleisten-Links');
@define('NAV_LINK_URL', 'URL des Navigationsleisten-Links');
